{
  "table": {
      "rows": [
          {
              "id": "1",
              "APELLIDO": "AGUILAR",
              "NOMBRE": "EDUARDO ALBERTO",
              "PROVINCIA": "CHACO",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "eduardo.aguilar@senado.gob.ar",
              "TELEFONO": "1200/01",
              "FACEBOOK": "https://www.facebook.com/EduardoAguilarChaco/",
              "TWITTER": "https://twitter.com/eduar_aguilar",
              "INSTAGRAM": "https://instagram.com/",
              "YOUTUBE": "https://youtube.com/user/liceduardoaguilar"

          },
          {
              "id": "2",
              "APELLIDO": "ALMIRÓN",
              "NOMBRE": "ANA CLAUDIA",
              "PROVINCIA": "CORRIENTES",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "ana.almiron@senado.gob.ar",
              "TELEFONO": "1026/22",
              "FACEBOOK": "https://www.facebook.com/anaalmironcorrientes/",
              "TWITTER": "https://twitter.com/AnitaAlmiron",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "3",
              "APELLIDO": "ALPEROVICH",
              "NOMBRE": "JOSÉ JORGE",
              "PROVINCIA": "TUCUMÁN",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "PERONISMO TUCUMAN",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "jose.alperovich@senado.gob.ar",
              "TELEFONO": "1355/56/57",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/JalperovichOK",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "4",
              "APELLIDO": "BASUALDO",
              "NOMBRE": "ROBERTO GUSTAVO",
              "PROVINCIA": "SAN JUAN",
              "PARTIDO": "ALIANZA CAMBIEMOS SAN JUAN",
              "BLOQUE": "PRODUCCIÓN Y TRABAJO",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "roberto.basualdo@senado.gob.ar",
              "TELEFONO": "1250/51/52/53/54/55",
              "FACEBOOK": "https://www.facebook.com/rgbasualdo/",
              "TWITTER": "https://twitter.com/RGBasualdo",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "5",
              "APELLIDO": "BLAS",
              "NOMBRE": "INÉS IMELDA",
              "PROVINCIA": "CATAMARCA",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "ines.blas@senado.gob.ar",
              "TELEFONO": "1401/03 - 1415",
              "FACEBOOK": "https://www.facebook.com/senadorainesblas/?fref=ts",
              "TWITTER": "https://twitter.com/SenadoraBlas",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "6",
              "APELLIDO": "BOYADJIAN",
              "NOMBRE": "MIRIAM RUTH",
              "PROVINCIA": "TIERRA DEL FUEGO, ANTÁRTIDA E ISLAS DEL ATLÁNTICO SUR",
              "PARTIDO": "MOVIMIENTO POPULAR FUEGUINO",
              "BLOQUE": "MOVIMIENTO POPULAR FUEGUINO",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2015-09-16",
              "C_REAL": "Sin Datos",
              "EMAIL": "miriam.boyadjian@senado.gob.ar",
              "TELEFONO": "1092/93",
              "FACEBOOK": "https://www.facebook.com/miriam.boyadjian/?fref=ts",
              "TWITTER": "https://twitter.com/BoyadjianMiriam",
              "INSTAGRAM": "https://www.instagram.com/miriamboyadjian/?hl=es-la",
              "YOUTUBE": ""

          },
          {
              "id": "7",
              "APELLIDO": "BRAILLARD POCCARD",
              "NOMBRE": "NÉSTOR PEDRO",
              "PROVINCIA": "CORRIENTES",
              "PARTIDO": "ALIANZA ENCUENTRO CORRIENTES",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "nestor.braillardpoccard@senado.gob.ar",
              "TELEFONO": "3186/87/88/89",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "8",
              "APELLIDO": "BRIZUELA Y DORIA DE CARA",
              "NOMBRE": "OLGA INES",
              "PROVINCIA": "LA RIOJA",
              "PARTIDO": "CAMBIEMOS FUERZA CIVICA RIOJANA",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "ines.brizuela@senado.gob.ar",
              "TELEFONO": "8702-1436",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "9",
              "APELLIDO": "BULLRICH",
              "NOMBRE": "ESTEBAN JOSE",
              "PROVINCIA": "BUENOS AIRES",
              "PARTIDO": "CAMBIEMOS BUENOS AIRES",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "esteban.bullrich@senado.gob.ar",
              "TELEFONO": "1045-1046-1055",
              "FACEBOOK": "https://www.facebook.com/estebanbullrich",
              "TWITTER": "https://twitter.com/@estebanbullrich",
              "INSTAGRAM": "https://www.instagram.com/estebanbullrich",
              "YOUTUBE": "https://www.youtube.com/estebanbullrich"

          },
          {
              "id": "10",
              "APELLIDO": "CASERIO",
              "NOMBRE": "CARLOS ALBERTO",
              "PROVINCIA": "CÓRDOBA",
              "PARTIDO": "ALIANZA UNIÓN POR CÓRDOBA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "carlos.caserio@senado.gob.ar",
              "TELEFONO": "1380/14/54/49",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "11",
              "APELLIDO": "CASTILLO",
              "NOMBRE": "OSCAR ANÍBAL",
              "PROVINCIA": "CATAMARCA",
              "PARTIDO": "FRENTE CÍVICO Y SOCIAL",
              "BLOQUE": "FRENTE CÍVICO Y SOCIAL DE CATAMARCA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "castillo@senado.gob.ar",
              "TELEFONO": "1395 - 1398",
              "FACEBOOK": "https://www.facebook.com/senador.oscar.castillo/",
              "TWITTER": "https://twitter.com/Oacastillo",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "12",
              "APELLIDO": "CATALÁN MAGNI",
              "NOMBRE": "JULIO CÉSAR",
              "PROVINCIA": "TIERRA DEL FUEGO, ANTÁRTIDA E ISLAS DEL ATLÁNTICO SUR",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "julio.catalanmagni@senado.gob.ar",
              "TELEFONO": "3462- 3464 - 3465",
              "FACEBOOK": "https://www.facebook.com/JulioCatalanMagni",
              "TWITTER": "https://twitter.com/j_catalanmagni",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "13",
              "APELLIDO": "CATALFAMO",
              "NOMBRE": "MARÍA EUGENIA",
              "PROVINCIA": "SAN LUIS",
              "PARTIDO": "FRENTE UNIDAD JUSTICIALISTA SAN LUIS",
              "BLOQUE": "JUSTICIALISMO SAN LUIS",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "eugenia.catalfamo@senado.gob.ar",
              "TELEFONO": "1520-1521-1524",
              "FACEBOOK": "https://www.facebook.com/eugeniacatalfamoSL/",
              "TWITTER": "https://twitter.com/eugecatalfamo",
              "INSTAGRAM": "https://www.instagram.com/eugeniacatalfamo",
              "YOUTUBE": "https://www.youtube.com/channel/UCQzZtEZT6db5egLfHAzPqQw/featured"

          },
          {
              "id": "14",
              "APELLIDO": "CLOSS",
              "NOMBRE": "MAURICE FABIÁN",
              "PROVINCIA": "MISIONES",
              "PARTIDO": "FRENTE RENOVADOR DE LA CONCORDIA",
              "BLOQUE": "MISIONES",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "SenadorCloss@senado.gob.ar",
              "TELEFONO": "3240 - 3285 3288",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "15",
              "APELLIDO": "COBOS",
              "NOMBRE": "JULIO CÉSAR CLETO",
              "PROVINCIA": "MENDOZA",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "julio.cobos@senado.gob.ar",
              "TELEFONO": "1451 -1453",
              "FACEBOOK": "https://www.facebook.com/JulioCesarCobos",
              "TWITTER": "https://twitter.com/@juliocobos",
              "INSTAGRAM": "https://www.instagram.com/julio.cesar.cobos/",
              "YOUTUBE": "https://youtube.com/"

          },
          {
              "id": "16",
              "APELLIDO": "COSTA",
              "NOMBRE": "EDUARDO RAÚL",
              "PROVINCIA": "SANTA CRUZ",
              "PARTIDO": "UNION PARA VIVIR MEJOR CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "eduardo.costa@senado.gob.ar",
              "TELEFONO": "3408-3410-3411-3413",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "17",
              "APELLIDO": "CREXELL",
              "NOMBRE": "CARMEN LUCILA",
              "PROVINCIA": "NEUQUÉN",
              "PARTIDO": "MOVIMIENTO POPULAR NEUQUINO",
              "BLOQUE": "MOVIMIENTO POPULAR NEUQUINO",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "lucila.crexell@senado.gob.ar",
              "TELEFONO": "3550",
              "FACEBOOK": "https://www.facebook.com/lucilacrexell/?fref=ts",
              "TWITTER": "https://twitter.com/LucilaCrexell",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "18",
              "APELLIDO": "DE ANGELI",
              "NOMBRE": "ALFREDO LUIS",
              "PROVINCIA": "ENTRE RÍOS",
              "PARTIDO": "ALIANZA UNIÓN POR ENTRE RÍOS",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "alfredo.deangeli@senado.gob.ar",
              "TELEFONO": "3580/81/82/83/84",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/alfredodeangeli",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "19",
              "APELLIDO": "DURANGO",
              "NOMBRE": "NORMA HAYDÉE",
              "PROVINCIA": "LA PAMPA",
              "PARTIDO": "ALIANZA FRENTE P/VICTORIA (PERONISMO PAMPEANO)",
              "BLOQUE": "PARTIDO JUSTICIALISTA LA PAMPA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "norma.durango@senado.gob.ar",
              "TELEFONO": "1330/31",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/norma_durango",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "20",
              "APELLIDO": "ELÍAS DE PEREZ",
              "NOMBRE": "SILVIA BEATRIZ",
              "PROVINCIA": "TUCUMÁN",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "silvia.elias@senado.gob.ar",
              "TELEFONO": "3508/09/10/11/12/13",
              "FACEBOOK": "https://www.facebook.com/silvia.eliasdeperez",
              "TWITTER": "https://twitter.com/silviaEdePerez",
              "INSTAGRAM": "https://www.instagram.com/silviaedeperez",
              "YOUTUBE": ""

          },
          {
              "id": "21",
              "APELLIDO": "ESPÍNOLA",
              "NOMBRE": "CARLOS MAURICIO",
              "PROVINCIA": "CORRIENTES",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "carlos.espinola@senado.gob.ar",
              "TELEFONO": "1222/23/24/25 -3183 -3190",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/espinolacamau",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "22",
              "APELLIDO": "FERNÁNDEZ DE KIRCHNER",
              "NOMBRE": "CRISTINA E.",
              "PROVINCIA": "BUENOS AIRES",
              "PARTIDO": "UNIDAD CIUDADANA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "cristina.fernandez@senado.gob.ar",
              "TELEFONO": "1315 / 17 / 18",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "23",
              "APELLIDO": "FERNÁNDEZ SAGASTI",
              "NOMBRE": "ANABEL",
              "PROVINCIA": "MENDOZA",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "anabel.fernandezsagasti@senado.gob.ar",
              "TELEFONO": "1060 -1069 - 8905/06",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/afernandezk",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "24",
              "APELLIDO": "FIAD",
              "NOMBRE": "MARIO RAYMUNDO",
              "PROVINCIA": "JUJUY",
              "PARTIDO": "FRENTE JUJEÑO CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "mario.fiad@senado.gob.ar",
              "TELEFONO": "3321-3358",
              "FACEBOOK": "https://www.facebook.com/MarioFiad/",
              "TWITTER": "https://twitter.com/MarioFiad",
              "INSTAGRAM": "https://www.instagram.com/mariofiad/",
              "YOUTUBE": "https://www.youtube.com/user/MarioFiadJujuy"

          },
          {
              "id": "25",
              "APELLIDO": "FIORE VIÑUALES",
              "NOMBRE": "MARÍA CRISTINA DEL VALLE",
              "PROVINCIA": "SALTA",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "PARES",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "maria.fiorevinuales@senado.gob.ar",
              "TELEFONO": "3568 - 3571",
              "FACEBOOK": "https://www.facebook.com/CristinaFioreV/",
              "TWITTER": "https://twitter.com/fiore_cristina/",
              "INSTAGRAM": "https://www.instagram.com/cristina_fiorev/",
              "YOUTUBE": "https://youtube.com/"

          },
          {
              "id": "26",
              "APELLIDO": "FUENTES",
              "NOMBRE": "MARCELO JORGE",
              "PROVINCIA": "NEUQUÉN",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "marcelo.fuentes@senado.gob.ar",
              "TELEFONO": "1467/69",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "27",
              "APELLIDO": "GARCÍA LARRABURU",
              "NOMBRE": "SILVINA MARCELA",
              "PROVINCIA": "RÍO NEGRO",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "silvina.garcialarraburu@senado.gob.ar",
              "TELEFONO": "3588 - 3590",
              "FACEBOOK": "https://www.facebook.com/Silvina-García-Larraburu-147895613528/",
              "TWITTER": "https://twitter.com/",
              "INSTAGRAM": "https://instagram.com/garcialarraburu/",
              "YOUTUBE": "https://youtube.com/channel/UCfsYLk17ffJTNto2_ScC7jQ"

          },
          {
              "id": "28",
              "APELLIDO": "GIACOPPO",
              "NOMBRE": "SILVIA DEL ROSARIO",
              "PROVINCIA": "JUJUY",
              "PARTIDO": "FRENTE JUJEÑO CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "silvia.giacoppo@senado.gob.ar",
              "TELEFONO": "1230 - 8855 - 8718",
              "FACEBOOK": "https://www.facebook.com/SilviaGiacoppoUCR",
              "TWITTER": "https://twitter.com/giacopposilvia",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "29",
              "APELLIDO": "GONZÁLEZ",
              "NOMBRE": "GLADYS ESTHER",
              "PROVINCIA": "BUENOS AIRES",
              "PARTIDO": "CAMBIEMOS BUENOS AIRES",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2017-12-27",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-27",
              "C_REAL": "Sin Datos",
              "EMAIL": "gladys.gonzalez@senado.gob.ar",
              "TELEFONO": "1066-3574-3576-3577",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "30",
              "APELLIDO": "GONZÁLEZ",
              "NOMBRE": "MARÍA TERESA MARGARITA",
              "PROVINCIA": "FORMOSA",
              "PARTIDO": "FRENTE DE LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "maria.gonzalez@senado.gob.ar",
              "TELEFONO": "1325-1327 Anexo: 3150",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "31",
              "APELLIDO": "GONZÁLEZ",
              "NOMBRE": "NANCY SUSANA",
              "PROVINCIA": "CHUBUT",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "nancy.gonzalez@senado.gob.ar",
              "TELEFONO": "3302 - 3379 -3390",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/nancysgonzalez",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "32",
              "APELLIDO": "GUASTAVINO",
              "NOMBRE": "PEDRO GUILLERMO ÁNGEL",
              "PROVINCIA": "ENTRE RÍOS",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "pedro.guastavino@senado.gob.ar",
              "TELEFONO": "1440 - 1444",
              "FACEBOOK": "https://www.facebook.com/pemoGuastavino",
              "TWITTER": "https://twitter.com/pemoguastavino",
              "INSTAGRAM": "https://instagram.com/pemoguastavino",
              "YOUTUBE": "https://youtube.com/channel/UCRYfEY8gdNLQT-MEduBfJnw"

          },
          {
              "id": "33",
              "APELLIDO": "IANNI",
              "NOMBRE": "ANA MARÍA",
              "PROVINCIA": "SANTA CRUZ",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "ana.ianni@senado.gob.ar",
              "TELEFONO": "1080-5587",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "34",
              "APELLIDO": "ITÚRREZ DE CAPPELLINI",
              "NOMBRE": "ADA ROSA DEL VALLE",
              "PROVINCIA": "SANTIAGO DEL ESTERO",
              "PARTIDO": "FRENTE CÍVICO POR SANTIAGO",
              "BLOQUE": "FRENTE CÍVICO POR SANTIAGO",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "ada.iturrez@senado.gob.ar",
              "TELEFONO": "1350 -1353",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "35",
              "APELLIDO": "KUNATH",
              "NOMBRE": "SIGRID ELISABETH",
              "PROVINCIA": "ENTRE RÍOS",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "sigrid.kunath@senado.gob.ar",
              "TELEFONO": "1305 - 1307 -1310",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/SigridKunath",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "36",
              "APELLIDO": "LÓPEZ VALVERDE",
              "NOMBRE": "CRISTINA DEL CARMEN",
              "PROVINCIA": "SAN JUAN",
              "PARTIDO": "FRENTE TODOS",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "cristina.lopez@senado.gob.ar",
              "TELEFONO": "1341-1342",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "37",
              "APELLIDO": "LOVERA",
              "NOMBRE": "DANIEL ANÍBAL",
              "PROVINCIA": "LA PAMPA",
              "PARTIDO": "ALIANZA FRENTE P/VICTORIA (PERONISMO PAMPEANO)",
              "BLOQUE": "PARTIDO JUSTICIALISTA LA PAMPA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "daniel.lovera@senado.gob.ar",
              "TELEFONO": "1474/75/76/77 -1479",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "38",
              "APELLIDO": "LUENZO",
              "NOMBRE": "ALFREDO HÉCTOR",
              "PROVINCIA": "CHUBUT",
              "PARTIDO": "CHUBUT SOMOS TODOS",
              "BLOQUE": "CHUBUT SOMOS TODOS",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "alfredo.luenzo@senado.gob.ar",
              "TELEFONO": "1282 - 1287",
              "FACEBOOK": "https://www.facebook.com/Senador-Alfredo-Luenzo-127058484332074/",
              "TWITTER": "https://twitter.com/SenadorLuenzo",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "39",
              "APELLIDO": "MARINO",
              "NOMBRE": "JUAN CARLOS",
              "PROVINCIA": "LA PAMPA",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "juan.marino@senado.gob.ar",
              "TELEFONO": "3536/37/38/39",
              "FACEBOOK": "https://www.facebook.com/marinojuancarlos",
              "TWITTER": "https://twitter.com/Juancmarino",
              "INSTAGRAM": "https://instagram.com/jc.marino",
              "YOUTUBE": "https://youtube.com/Marinovideos"

          },
          {
              "id": "40",
              "APELLIDO": "MARTÍNEZ",
              "NOMBRE": "ERNESTO FÉLIX",
              "PROVINCIA": "CÓRDOBA",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "ernesto.martinez@senado.gob.ar",
              "TELEFONO": "1374 - 1376",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "41",
              "APELLIDO": "MARTÍNEZ",
              "NOMBRE": "JULIO CÉSAR",
              "PROVINCIA": "LA RIOJA",
              "PARTIDO": "CAMBIEMOS FUERZA CIVICA RIOJANA",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "julio.martinez@senado.gob.ar",
              "TELEFONO": "1320-1321-1324-1326",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "42",
              "APELLIDO": "MAYANS",
              "NOMBRE": "JOSÉ MIGUEL ÁNGEL",
              "PROVINCIA": "FORMOSA",
              "PARTIDO": "FRENTE DE LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "mayans@senado.gob.ar",
              "TELEFONO": "1023 - 1036 - 1037 - 1039",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "43",
              "APELLIDO": "MENEM",
              "NOMBRE": "CARLOS SAÚL",
              "PROVINCIA": "LA RIOJA",
              "PARTIDO": "FRENTE JUSTICIALISTA RIOJANO",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "carlos.menem@senado.gob.ar",
              "TELEFONO": "1008 - 1009",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "44",
              "APELLIDO": "MERA",
              "NOMBRE": "DALMACIO",
              "PROVINCIA": "CATAMARCA",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "dalmacio.mera@senado.gob.ar",
              "TELEFONO": "3440 - 3443 -3444",
              "FACEBOOK": "https://www.facebook.com/dalmaciomera",
              "TWITTER": "https://twitter.com/dalmaciomera",
              "INSTAGRAM": "https://instagram.com/dalmaciomera",
              "YOUTUBE": "https://youtube.com/dalmaciomera"

          },
          {
              "id": "45",
              "APELLIDO": "MIRKIN",
              "NOMBRE": "BEATRIZ GRACIELA",
              "PROVINCIA": "TUCUMÁN",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "PERONISMO TUCUMAN",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "beatriz.mirkin@senado.gob.ar",
              "TELEFONO": "3471/72 - 3475",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "46",
              "APELLIDO": "MONTENEGRO",
              "NOMBRE": "GERARDO ANTENOR",
              "PROVINCIA": "SANTIAGO DEL ESTERO",
              "PARTIDO": "FRENTE POPULAR",
              "BLOQUE": "FRENTE POPULAR",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "gerardo.montenegro@senado.gob.ar",
              "TELEFONO": "3504 - 3512 - 3521 - 3526",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "47",
              "APELLIDO": "ODARDA",
              "NOMBRE": "MARÍA MAGDALENA",
              "PROVINCIA": "RÍO NEGRO",
              "PARTIDO": "ALIANZA FRENTE PROGRESISTA",
              "BLOQUE": "RIO - FRENTE PROGRESISTA",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "maria.odarda@senado.gob.ar",
              "TELEFONO": "3556/57/58/59",
              "FACEBOOK": "https://www.facebook.com/magdalenaodardaoficial",
              "TWITTER": "https://twitter.com/MagdalenaOdarda",
              "INSTAGRAM": "https://www.instagram.com/magdalenaodarda/",
              "YOUTUBE": ""

          },
          {
              "id": "48",
              "APELLIDO": "OJEDA",
              "NOMBRE": "JOSÉ ANATOLIO",
              "PROVINCIA": "TIERRA DEL FUEGO, ANTÁRTIDA E ISLAS DEL ATLÁNTICO SUR",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "jose.ojeda@senado.gob.ar",
              "TELEFONO": "1487/88 - 1511/12/13",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "49",
              "APELLIDO": "PAIS",
              "NOMBRE": "JUAN MARIO",
              "PROVINCIA": "CHUBUT",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA CHUBUT",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "juan.pais@senado.gob.ar",
              "TELEFONO": "1370/71/72",
              "FACEBOOK": "https://www.facebook.com/Juan-Mario-Pais-1637635439805075/",
              "TWITTER": "https://twitter.com/juanmariopais",
              "INSTAGRAM": "https://www.instagram.com/senadorpais/",
              "YOUTUBE": ""

          },
          {
              "id": "50",
              "APELLIDO": "PEREYRA",
              "NOMBRE": "GUILLERMO JUAN",
              "PROVINCIA": "NEUQUÉN",
              "PARTIDO": "MOVIMIENTO POPULAR NEUQUINO",
              "BLOQUE": "MOVIMIENTO POPULAR NEUQUINO",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "guillermo.pereyra@senado.gob.ar",
              "TELEFONO": "1490/95",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/SenadorPereyra",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "51",
              "APELLIDO": "PEROTTI",
              "NOMBRE": "OMAR ÁNGEL",
              "PROVINCIA": "SANTA FE",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "omar.perotti@senado.gob.ar",
              "TELEFONO": "1210 - 1213 - 5846",
              "FACEBOOK": "https://www.facebook.com/omarperotti",
              "TWITTER": "https://twitter.com/omarperotti",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "52",
              "APELLIDO": "PETCOFF NAIDENOFF",
              "NOMBRE": "LUIS CARLOS",
              "PROVINCIA": "FORMOSA",
              "PARTIDO": "FRENTE AMPLIO FORMOSEÑO CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "luis.petcoffnaidenoff@senado.gob.ar",
              "TELEFONO": "3543/46",
              "FACEBOOK": "https://www.facebook.com/luisnaidenoff",
              "TWITTER": "https://twitter.com/luisnaidenoff",
              "INSTAGRAM": "https://www.instagram.com/luisnaidenoff",
              "YOUTUBE": "https://www.youtube.com/SenadorNaidenoff"

          },
          {
              "id": "53",
              "APELLIDO": "PICHETTO",
              "NOMBRE": "MIGUEL ÁNGEL",
              "PROVINCIA": "RÍO NEGRO",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "PERONISMO REPUBLICANO RIO NEGRO",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "pichetto@senado.gob.ar",
              "TELEFONO": "1380",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "54",
              "APELLIDO": "PILATTI VERGARA",
              "NOMBRE": "MARÍA INÉS",
              "PROVINCIA": "CHACO",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "maria.pilattivergara@senado.gob.ar",
              "TELEFONO": "3422 - 3424/25 - 5589",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/pilattivergara",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "55",
              "APELLIDO": "PINEDO",
              "NOMBRE": "FEDERICO",
              "PROVINCIA": "CIUDAD AUTÓNOMA de BUENOS AIRES",
              "PARTIDO": "ALIANZA UNIÓN PRO",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "federico.pinedo@senado.gob.ar",
              "TELEFONO": "1084 - 1098",
              "FACEBOOK": "https://www.facebook.com/federicopinedo",
              "TWITTER": "https://twitter.com/PinedoFederico",
              "INSTAGRAM": "https://instagram.com/pinedo.federico/",
              "YOUTUBE": "https://youtube.com/user/ProPinedo"

          },
          {
              "id": "56",
              "APELLIDO": "POGGI",
              "NOMBRE": "CLAUDIO JAVIER",
              "PROVINCIA": "SAN LUIS",
              "PARTIDO": "AVANZAR Y CAMBIEMOS POR SAN LUIS",
              "BLOQUE": "AVANZAR SAN LUIS",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "claudio.poggi@senado.gob.ar",
              "TELEFONO": "3415-3416-3417-3420",
              "FACEBOOK": "https://www.facebook.com/claudio.javier.poggi",
              "TWITTER": "https://twitter.com/claudiojpoggi",
              "INSTAGRAM": "https://www.instagram.com/claudiojpoggi",
              "YOUTUBE": ""

          },
          {
              "id": "57",
              "APELLIDO": "PORCEL DE RICCOBELLI",
              "NOMBRE": "BLANCA",
              "PROVINCIA": "SANTIAGO DEL ESTERO",
              "PARTIDO": "ALIANZA FRENTE CÍVICO",
              "BLOQUE": "FRENTE CÍVICO POR SANTIAGO",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "blanca.porcel@senado.gob.ar",
              "TELEFONO": "1064-8835",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "58",
              "APELLIDO": "REUTEMANN",
              "NOMBRE": "CARLOS ALBERTO",
              "PROVINCIA": "SANTA FE",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "SANTA FE FEDERAL",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "reuteman@senado.gob.ar",
              "TELEFONO": "1422/26",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/ReutemannC",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "59",
              "APELLIDO": "RODRÍGUEZ MACHADO",
              "NOMBRE": "LAURA ELENA",
              "PROVINCIA": "CÓRDOBA",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "laura.rodriguezmachado@senado.gob.ar",
              "TELEFONO": "3290/91",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/laurmachado",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "60",
              "APELLIDO": "RODRÍGUEZ SAÁ",
              "NOMBRE": "ADOLFO",
              "PROVINCIA": "SAN LUIS",
              "PARTIDO": "FRENTE UNIDAD JUSTICIALISTA SAN LUIS",
              "BLOQUE": "UNIDAD JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "adolfo.rodriguezsaa@senado.gob.ar",
              "TELEFONO": "1501 - 1503",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "61",          
              "APELLIDO": "ROMERO",
              "NOMBRE": "JUAN CARLOS",
              "PROVINCIA": "SALTA",
              "PARTIDO": "FRENTE POPULAR SALTEÑO",
              "BLOQUE": "JUSTICIALISTA 8 DE OCTUBRE",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "juan.romero@senado.gob.ar",
              "TELEFONO": "5673 - 5675",
              "FACEBOOK": "https://www.facebook.com/romeroxsalta",
              "TWITTER": "https://twitter.com/romeroxsalta",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "62",          
              "APELLIDO": "ROZAS",
              "NOMBRE": "ÁNGEL",
              "PROVINCIA": "CHACO",
              "PARTIDO": "UNIÓN POR CHACO",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "angel.rozas@senado.gob.ar",
              "TELEFONO": "3522/25",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/angelrozaschaco",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "63",
              "APELLIDO": "SACNUN",
              "NOMBRE": "MARÍA DE LOS ÁNGELES",
              "PROVINCIA": "SANTA FE",
              "PARTIDO": "ALIANZA FRENTE PARA LA VICTORIA",
              "BLOQUE": "FRENTE PARA LA VICTORIA - PJ",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "maria.sacnun@senado.gob.ar",
              "TELEFONO": "3562 - 3564 -3565",
              "FACEBOOK": "https://www.facebook.com/www.marilinsacnun.com.ar/",
              "TWITTER": "https://twitter.com/sacnun",
              "INSTAGRAM": "https://www.instagram.com/marilinsacnun/?hl=es-la",
              "YOUTUBE": "https://www.youtube.com/channel/UCPA9vsOomZLM0M1IS4ealnQ?view_as=subscriber"

          },
          {
              "id": "64",
              "APELLIDO": "SCHIAVONI",
              "NOMBRE": "HUMBERTO LUIS ARTURO",
              "PROVINCIA": "MISIONES",
              "PARTIDO": "FRENTE CAMBIEMOS",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "humberto.schiavoni@senado.gob.ar",
              "TELEFONO": "1051",
              "FACEBOOK": "https://www.facebook.com/humberto.schiavoni",
              "TWITTER": "https://twitter.com/schiavonih",
              "INSTAGRAM": "https://www.instagram.com/humbertoschiavoni",
              "YOUTUBE": "https://www.youtube.com/channel/UC-cYG8bNmK66jNs-K5iiGcQ/featured"

          },
          {
              "id": "65",
              "APELLIDO": "SNOPEK",
              "NOMBRE": "GUILLERMO EUGENIO MARIO",
              "PROVINCIA": "JUJUY",
              "PARTIDO": "FRENTE JUSTICIALISTA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "guillermo.snopek@senado.gob.ar",
              "TELEFONO": "1480-1481-1482-1483",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "66",
              "APELLIDO": "SOLANAS",
              "NOMBRE": "FERNANDO EZEQUIEL",
              "PROVINCIA": "CIUDAD AUTÓNOMA de BUENOS AIRES",
              "PARTIDO": "ALIANZA UNEN",
              "BLOQUE": "PROYECTO SUR-UNEN",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "fernando.solanas@senado.gob.ar",
              "TELEFONO": "1384/86 - 1389/90",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/fernandosolanas",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "67",
              "APELLIDO": "SOLARI  QUINTANA",
              "NOMBRE": "MAGDALENA",
              "PROVINCIA": "MISIONES",
              "PARTIDO": "FRENTE RENOVADOR DE LA CONCORDIA",
              "BLOQUE": "MISIONES",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "magdalena.solariquintana@senado.gob.ar",
              "TELEFONO": "3535-3540-3542",
              "FACEBOOK": "https://www.facebook.com/profile.php?id=100020484819650",
              "TWITTER": "https://twitter.com/MaggieSolariQ",
              "INSTAGRAM": "https://www.instagram.com/maggiesolariq/",
              "YOUTUBE": ""

          },
          {
              "id": "68",
              "APELLIDO": "TAPIA",
              "NOMBRE": "MARÍA BELÉN",
              "PROVINCIA": "SANTA CRUZ",
              "PARTIDO": "UNION PARA VIVIR MEJOR CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "maria.tapia@senado.gob.ar",
              "TELEFONO": "3451-3452-3453",
              "FACEBOOK": "María Belén Tapia - Senadora Nacional",
              "TWITTER": "MariabTapia",
              "INSTAGRAM": "tapia_senadoranacional/",
              "YOUTUBE": ""

          },
          {
              "id": "69",
              "APELLIDO": "UÑAC",
              "NOMBRE": "JOSÉ RUBÉN",
              "PROVINCIA": "SAN JUAN",
              "PARTIDO": "FRENTE TODOS",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2017-12-10",
              "C_LEGAL": "2023-12-09",
              "D_REAL": "2017-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "jose.unac@senado.gob.ar",
              "TELEFONO": "1429-1431-1433",
              "FACEBOOK": "",
              "TWITTER": "",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "70",
              "APELLIDO": "URTUBEY",
              "NOMBRE": "RODOLFO JULIO",
              "PROVINCIA": "SALTA",
              "PARTIDO": "FRENTE PARA LA VICTORIA",
              "BLOQUE": "JUSTICIALISTA",
              "D_LEGAL": "2013-12-10",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2013-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "rodolfo.urtubey@senado.gov.ar",
              "TELEFONO": "1300/1303",
              "FACEBOOK": "",
              "TWITTER": "https://twitter.com/tolourtubey",
              "INSTAGRAM": "",
              "YOUTUBE": ""

          },
          {
              "id": "71",
              "APELLIDO": "VARELA",
              "NOMBRE": "MARTA",
              "PROVINCIA": "CIUDAD AUTÓNOMA de BUENOS AIRES",
              "PARTIDO": "ALIANZA UNIÓN PRO",
              "BLOQUE": "FRENTE PRO",
              "D_LEGAL": "2016-02-11",
              "C_LEGAL": "2019-12-09",
              "D_REAL": "2016-02-11",
              "C_REAL": "Sin Datos",
              "EMAIL": "marta.varela@senado.gob.ar",
              "TELEFONO": "3456 - 3457/58",
              "FACEBOOK": "https://www.facebook.com/MartaVarela15/",
              "TWITTER": "https://twitter.com/MLVarela",
              "INSTAGRAM": "https://www.instagram.com/martaluciavarela",
              "YOUTUBE": ""

          },
          {
              "id": "72",
              "APELLIDO": "VERASAY",
              "NOMBRE": "PAMELA FERNANDA",
              "PROVINCIA": "MENDOZA",
              "PARTIDO": "ALIANZA CAMBIEMOS",
              "BLOQUE": "UNIÓN CÍVICA RADICAL",
              "D_LEGAL": "2015-12-10",
              "C_LEGAL": "2021-12-09",
              "D_REAL": "2015-12-10",
              "C_REAL": "Sin Datos",
              "EMAIL": "pamela.verasay@senado.gob.ar",
              "TELEFONO": "3500 - 3502",
              "FACEBOOK": "https://www.facebook.com/PamelaVerasayUCR/",
              "TWITTER": "https://twitter.com/PameVerasay",
              "INSTAGRAM": "https://instagram.com/pamela.verasay/",
              "YOUTUBE": "https://youtube.com/"

          }
  ]
  }
  }